name: molecular-dynamics

channels:
    - default
    - conda-forge

dependencies:
    - python>=3.9
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - pycodestyle
    - pydocstyle
    - pylint

